// Desenvolva um algoritmo que leia um vetor de 20 posições inteiras e o coloque
// em ordem
// crescente, utilizando a seguinte estratégia de ordenação:
// - selecione o elemento do vetor de 20 posiçÕes que apresenta o menor valor;
// - troque este elemento pelo primeiro;
// - repita estas operações, envolvendo agora apenas os 19 elementos restantes
// (selecionando o de menor valor com a segunda posição, deois os 18 elementos
// trocando o de menor valor com a terceira posição), depois os 17, os 16 e
// assim por diante, até restar um único elemento, o maior deles.