{*
 * Programa
 * Descriçao
 *
 *
 * @pacote
 * @autor
 * @copyright
 * @lisense
 * @link
 * @desde
 * @dependentes
 *}

{*----------------------------------------------------------------------------*}
Algoritmo "name"

{*----------------------------------------------------------------------------*}

{*
 * Cabeçalho e prototipos de procedures e functions
 * Tipo: Variaveis / constante / includes / definitions / functions / procedures
 *
 * @[tipo_abreviado ex var, const, inc, def, func, proc]
*}
var

{*----------------------------------------------------------------------------*}

{* Funcao Inicio *}
Inicio

    {* Constructor *}

    {*------------------------------------------------------------------------*}

    {*
     * Entrada
     *
     * Descricao
     *}
     
     limpatela

    {*------------------------------------------------------------------------*}

    {* Processamento *}

    {*------------------------------------------------------------------------*}

    {* Saida *}

    {*------------------------------------------------------------------------*}

    {* Destruidor *}

Fimalgoritmo


{*----------------------------------------------------------------------------*}

{* Implantaçao das Functions *}

{*
 * (_functionTemplate) - Template de fumçao
 * Descrição
 *
 * @tipo
 * @pacote
 * @categoria
 * @autor
 * @link
 *
 * @acesso
 * @param[in]
 * @param[out]
 * @return
 * @implementacao
*}

    {* Constructor *}

    {*------------------------------------------------------------------------*}

    {*
     * Entrada
     *
     * Descricao
     *}

    {*------------------------------------------------------------------------*}

    {* Processamento *}

    {*------------------------------------------------------------------------*}

    {* Saida *}

    {*------------------------------------------------------------------------*}

    {* Destruidor *}

{*----------------------------------------------------------------------------*}

{* Implantação dos Procedures *}

{*
 * (_procedureTemplate) - Template de procedimento
 * Descricao
 *
 * @tipo
 * @pacote
 * @categoria
 * @autor
 * @link
 *
 * @acesso
 * @param[in]
 * @param[out]
 * @implementacao
*}

    {* Constructor *}

    {*------------------------------------------------------------------------*}

    {*
     * Entrada
     *
     * Descricao
     *}

    {*------------------------------------------------------------------------*}

    {* Processamento *}

    {*------------------------------------------------------------------------*}

    {* Saida *}

    {*------------------------------------------------------------------------*}

    {* Destruidor *}